version: '3'

services:

  app:
    image: latchchallenge:v1
    environment:
      - VIRTUAL_HOST=app.local
      - VIRTUAL_PORT=4000
    expose:
      - "4000"
    networks:
      - app_net
      - db_net

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/nginx.conf:/etc/nginx/nginx.conf
      - ./data/latch.crt:/etc/nginx/ssl/latch.crt
      - ./data/latch.key:/etc/nginx/ssl/latch.key
    networks:
      - app_net

  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
    restart: unless-stopped
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./data/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app_net
    depends_on:
      - app
      - blackbox_exporter 
  
  blackbox_exporter:
    image: prom/blackbox-exporter
    networks:
      - app_net

volumes:
  loki_data:

networks:
  app_net:
  db_net:
